

   name: Build Next.js and Upload .next

on:
  workflow_dispatch:   # allows manual trigger
  push:
    branches:
      - main           # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20   # match your Next.js version requirements

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Upload .next folder
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next
          
